# Generated by Django 5.2.5 on 2025-08-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=50)),
                ('case_year', models.CharField(max_length=4)),
                ('query_timestamp', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
